spring:
  application:
    name: property-view
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8092

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.core.env: DEBUG

---

spring:
  config:
    activate:
      on-profile: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Либо `none`, если используете Liquibase
    show-sql: true
  datasource:
    url: jdbc:h2:mem:propertydb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/property_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1006

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/property_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password


